steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '--build-arg', 'NEXT_PUBLIC_API_URL=$_BACKEND_URL',
      '-t', 'gcr.io/$PROJECT_ID/healytics-frontend:v1',
      '.'
    ]
images:
- 'gcr.io/$PROJECT_ID/healytics-frontend:v1'
substitutions:
  _BACKEND_URL: ''
