# .github/workflows/azure-acr.yml
name: Build & Push Healytics to ACR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) (Optional) enable Buildx if you ever need multi-arch, but plain docker works too
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Log in to ACR
      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}

      # 4) Build the image from the backend/ folder
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/healytics-backend:v1 \
            backend

      # 5) Push the image to ACR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/healytics-backend:v1
