# .github/workflows/azure-acr.yml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build & Push Healytics to ACR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Debug: show whether the registry secret is actually set
      - name: Debug ACR secret
        run: |
          echo ">> registry: '${{ secrets.ACR_LOGIN_SERVER }}'"
          echo ">> user:     '${{ secrets.ACR_USER }}'"

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/healytics-backend:v1 backend

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/healytics-backend:v1
