# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build & Push Healytics to ACR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username:     ${{ secrets.ACR_USER }}
          password:     ${{ secrets.ACR_PASS }}

      - name: Build & push image
        run: |
          # build using the backend/ folder as context
          docker build \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/healytics-backend:v1 \
            backend/
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/healytics-backend:v1
