# .github/workflows/azure-acr.yml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build & Push Healytics to ACR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASS }}

      - name: Build & push Docker image
        run: |
          # Build from the ./backend folder
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/healytics-backend:v1 ./backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/healytics-backend:v1
